import { useState } from "react";
import { Link } from "react-router-dom";
import { motion, AnimatePresence } from "motion/react";
import {
  FileSearch,
  GitMerge,
  Network,
  Bot,
  Activity,
  ShieldCheck,
  ChevronDown,
  ChevronUp,
  Sun,
  Moon,
  ArrowRight,
  Zap,
  TrendingDown,
  Target,
} from "lucide-react";
import { useTheme } from "../context/ThemeContext";

// ─── Types ────────────────────────────────────────────────────────────────────

interface Feature {
  id: string;
  icon: React.ReactNode;
  name: string;
  description: string;
  capabilities: string[];
  technicalDetail: string;
}

// ─── Data ─────────────────────────────────────────────────────────────────────

const FEATURES: Feature[] = [
  {
    id: "document-intelligence",
    icon: <FileSearch size={24} />,
    name: "Document Intelligence",
    description:
      "Deep PDF forensics powered by multi-layer OCR analysis and metadata scanning. Every pixel is interrogated for signs of manipulation.",
    capabilities: [
      "Forgery heatmaps",
      "AI-generated doc detection",
      "Signature verification",
    ],
    technicalDetail:
      "The Document Intelligence engine runs each uploaded PDF through a five-stage pipeline: raw binary inspection, pixel-level raster analysis, OCR confidence mapping, metadata timeline cross-check, and font fingerprinting. Any inconsistency at any stage immediately triggers a forensic flag.\n\nFor AI-generated documents, the system applies a custom CNN trained on 2.3 million synthetic document samples. The model produces a probabilistic confidence score per page region, distinguishing legitimate scanned documents from those generated by LLM-based document fabricators with 97.4% precision on our benchmark dataset.",
  },
  {
    id: "cross-document",
    icon: <GitMerge size={24} />,
    name: "Cross-Document Engine",
    description:
      "Income contradiction detection across salary slips, GST filings, ITR returns, and bank statements. One truth across all documents.",
    capabilities: [
      "12-point contradiction matrix",
      "Timeline intelligence",
      "Behavioral consistency scoring",
    ],
    technicalDetail:
      "The Cross-Document Engine maintains a shared entity graph across all documents in an investigation. Every monetary figure, date, employer name, and PAN number is normalized and projected onto a unified timeline. The 12-point contradiction matrix evaluates relationships like salary-to-bank-inflow ratio, GST turnover vs. declared income, and ITR net worth vs. property acquisitions.\n\nTimeline intelligence reconstructs a chronological narrative from disparate document dates, catching cases where a salary slip predates an employer's incorporation or where a bank statement shows inflows before a declared job start date. Behavioral consistency scoring assigns an anomaly probability to the full document set rather than flagging isolated individual discrepancies.",
  },
  {
    id: "fraud-graph",
    icon: <Network size={24} />,
    name: "Fraud Graph",
    description:
      "Entity relationship mapping across accounts, PANs, properties, and employers. Hidden rings become visible instantly.",
    capabilities: [
      "Fraud ring detection",
      "Real-time graph updates",
      "Relationship path tracing",
    ],
    technicalDetail:
      "Built on a Neo4j property graph, the Fraud Graph stores every extracted entity as a node — persons, accounts, PANs, properties, employers, and phone numbers — with typed edges representing relationships discovered from documents or cross-referenced from public registries. Graph traversal algorithms identify tightly connected clusters that indicate synthetic identity rings or coordinated loan fraud.\n\nFraud ring detection runs a modified Louvain community detection algorithm that surfaces groups of entities with disproportionately high internal edge density relative to external connections. Path tracing exposes the shortest relationship chain between any two entities, allowing an investigator to understand exactly how two apparently unrelated applicants share a common fraudulent origin.",
  },
  {
    id: "ai-investigator",
    icon: <Bot size={24} />,
    name: "AI Investigator",
    description:
      "Structured reasoning engine for analysts — not a chatbot. Builds evidence chains and delivers actionable verdicts with confidence scores.",
    capabilities: [
      "Evidence chain building",
      "Confidence scoring",
      "Actionable recommendations",
    ],
    technicalDetail:
      "The AI Investigator is a multi-step reasoning agent that operates over the full evidence set from document forensics, cross-document contradictions, and fraud graph findings. Using a chain-of-thought architecture, it produces a structured argument: hypothesis → supporting evidence → counter-evidence → weighted verdict. This is fundamentally different from a retrieval-augmented chatbot — the system reasons, not retrieves.\n\nConfidence scoring is calibrated against historical case outcomes using a Platt-scaled logistic model. Each generated recommendation cites the specific document field, page, and section from which the supporting evidence was extracted, creating a fully auditable evidence chain that survives legal scrutiny and satisfies RBI investigation documentation standards.",
  },
  {
    id: "real-time-monitoring",
    icon: <Activity size={24} />,
    name: "Real-Time Monitoring",
    description:
      "SOC-style live anomaly detection across your entire portfolio. Sub-second event processing with India regional heatmap overlays.",
    capabilities: [
      "Sub-second event processing",
      "India regional heatmap",
      "System load metrics",
    ],
    technicalDetail:
      "The Real-Time Monitoring module subscribes to a Kafka event stream that ingests signals from document uploads, application events, API calls, and external bureau feeds. A sliding-window anomaly detector applies Isolation Forest models to detect behavioral outliers in real time — flagging application clusters from the same IP range, unusual document submission timing, or sudden spikes in a geographic region.\n\nThe India regional heatmap renders fraud density at the district level using GeoJSON boundary data, updated every 30 seconds. Investigators can drill down from national overview to state to district to individual case cluster. System load metrics expose internal queue depths, model inference latencies, and storage throughput so operations teams can monitor pipeline health alongside fraud signals.",
  },
  {
    id: "compliance-center",
    icon: <ShieldCheck size={24} />,
    name: "Compliance Center",
    description:
      "RBI and AML compliance tracking with KYC gap detection and measurable action points. Stay audit-ready at all times.",
    capabilities: [
      "KYC gap detection",
      "AML risk flags",
      "Measurable Action Points",
    ],
    technicalDetail:
      "The Compliance Center maps every investigation finding against a live compliance rulebook that tracks RBI Master Circular requirements, PMLA AML obligations, and FATF risk assessment guidelines. KYC gap detection runs automatically on document ingestion, comparing submitted documents against required checklist items per customer risk category (low, medium, high, PEP).\n\nAML risk flags are generated using a rule-based engine layered over an ML scoring model trained on SAR (Suspicious Activity Report) filing patterns from cooperative institutions. Measurable Action Points are generated as structured tasks with due dates, responsible roles, and evidence references — turning compliance findings into trackable workflow items that integrate with case management systems via the REST API.",
  },
];

const STATS = [
  { icon: <Zap size={16} />, value: "92%", label: "Faster Investigations" },
  { icon: <TrendingDown size={16} />, value: "67%", label: "Fraud Reduction" },
  { icon: <Target size={16} />, value: "99.1%", label: "Detection Accuracy" },
];

const API_EXAMPLES = [
  {
    title: "REST API",
    subtitle: "HTTP/2 · JSON · Bearer Auth",
    code: `POST /api/v1/investigations
Authorization: Bearer <token>
Content-Type: application/json

{
  "case_id": "INV-2024-4521",
  "applicant_pan": "ABCDE1234F",
  "documents": [
    { "type": "salary_slip", "url": "s3://..." },
    { "type": "bank_statement", "url": "s3://..." },
    { "type": "itr_2023", "url": "s3://..." }
  ],
  "priority": "high"
}

// Response 202 Accepted
{
  "investigation_id": "trn_8f3a9b2c",
  "status": "processing",
  "eta_seconds": 87
}`,
  },
  {
    title: "Webhook Events",
    subtitle: "HMAC-SHA256 signed · Retry w/ backoff",
    code: `// POST to your endpoint on completion
{
  "event": "investigation.completed",
  "investigation_id": "trn_8f3a9b2c",
  "timestamp": "2024-01-15T14:23:11Z",
  "payload": {
    "risk_score": 94,
    "verdict": "HIGH_RISK",
    "contradictions_found": 7,
    "forgery_flags": 2,
    "fraud_ring_connection": true,
    "report_url": "https://trinetra.ai/reports/..."
  },
  "signature": "sha256=abc123..."
}`,
  },
  {
    title: "SDK Support",
    subtitle: "Python · Node.js · Go",
    code: `# Python SDK
from trinetra import Client

client = Client(api_key="trn_live_...")

investigation = client.investigations.create(
    case_id="INV-2024-4521",
    applicant_pan="ABCDE1234F",
    documents=[
        client.documents.upload("salary_slip.pdf"),
        client.documents.upload("bank_statement.pdf"),
    ],
)

# Wait for completion
result = investigation.wait()
print(f"Risk Score: {result.risk_score}/100")
print(f"Verdict: {result.verdict}")`,
  },
];

// ─── Sub-components ────────────────────────────────────────────────────────────

function PageNav() {
  const { c, isDark, toggleTheme } = useTheme();
  return (
    <nav
      style={{
        background: c.navBg,
        borderBottom: `1px solid ${c.border}`,
        backdropFilter: "blur(16px)",
        position: "sticky",
        top: 0,
        zIndex: 50,
      }}
    >
      <div
        style={{
          maxWidth: 1200,
          margin: "0 auto",
          padding: "0 24px",
          height: 60,
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 24 }}>
          <span
            style={{
              fontFamily: "'Syne', sans-serif",
              fontWeight: 800,
              fontSize: 18,
              color: c.text,
              letterSpacing: "-0.5px",
            }}
          >
            TRINETRA AI
          </span>
          <Link
            to="/"
            style={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontSize: 14,
              color: c.textMuted,
              textDecoration: "none",
              display: "flex",
              alignItems: "center",
              gap: 4,
            }}
          >
            ← Landing
          </Link>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <button
            onClick={toggleTheme}
            style={{
              background: "transparent",
              border: `1px solid ${c.border}`,
              borderRadius: 8,
              padding: "6px 10px",
              cursor: "pointer",
              color: c.textMuted,
              display: "flex",
              alignItems: "center",
            }}
          >
            {isDark ? <Sun size={15} /> : <Moon size={15} />}
          </button>
          <Link
            to="/workspace/hub"
            style={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontSize: 14,
              fontWeight: 600,
              color: "#fff",
              background: c.accent,
              textDecoration: "none",
              padding: "8px 16px",
              borderRadius: 8,
              display: "flex",
              alignItems: "center",
              gap: 6,
            }}
          >
            Open Workspace <ArrowRight size={14} />
          </Link>
        </div>
      </div>
    </nav>
  );
}

function Hero() {
  const { c } = useTheme();
  return (
    <section
      style={{
        background: c.bg,
        padding: "100px 24px 80px",
        textAlign: "center",
      }}
    >
      <div style={{ maxWidth: 800, margin: "0 auto" }}>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 8,
              background: c.accentLight,
              border: `1px solid ${c.accent}40`,
              borderRadius: 100,
              padding: "6px 16px",
              marginBottom: 28,
            }}
          >
            <ShieldCheck size={14} color={c.accent} />
            <span
              style={{
                fontFamily: "'Space Grotesk', sans-serif",
                fontSize: 13,
                color: c.accent,
                fontWeight: 500,
              }}
            >
              Platform Capabilities
            </span>
          </div>
          <h1
            style={{
              fontFamily: "'Syne', sans-serif",
              fontWeight: 800,
              fontSize: "clamp(2rem, 5vw, 3.5rem)",
              lineHeight: 1.1,
              color: c.text,
              marginBottom: 20,
              letterSpacing: "-1px",
            }}
          >
            The Complete Fraud
            <br />
            <span style={{ color: c.accent }}>Intelligence Platform</span>
          </h1>
          <p
            style={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontSize: 18,
              color: c.textMuted,
              lineHeight: 1.7,
              marginBottom: 48,
              maxWidth: 600,
              margin: "0 auto 48px",
            }}
          >
            TRINETRA combines document forensics, AI reasoning, graph analysis,
            and real-time monitoring into one unified investigation platform —
            built for India's financial crime landscape.
          </p>
          <div
            style={{
              display: "flex",
              justifyContent: "center",
              gap: 16,
              flexWrap: "wrap",
            }}
          >
            {STATS.map((stat) => (
              <div
                key={stat.label}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 10,
                  background: c.bgCard,
                  border: `1px solid ${c.border}`,
                  borderRadius: 100,
                  padding: "10px 20px",
                }}
              >
                <span style={{ color: c.accent }}>{stat.icon}</span>
                <span
                  style={{
                    fontFamily: "'Syne', sans-serif",
                    fontWeight: 700,
                    fontSize: 18,
                    color: c.text,
                  }}
                >
                  {stat.value}
                </span>
                <span
                  style={{
                    fontFamily: "'Space Grotesk', sans-serif",
                    fontSize: 13,
                    color: c.textMuted,
                  }}
                >
                  {stat.label}
                </span>
              </div>
            ))}
          </div>
        </motion.div>
      </div>
    </section>
  );
}

function FeatureGrid() {
  const { c } = useTheme();
  return (
    <section
      style={{ background: c.bgSecondary, padding: "80px 24px" }}
    >
      <div style={{ maxWidth: 1200, margin: "0 auto" }}>
        <div style={{ textAlign: "center", marginBottom: 56 }}>
          <h2
            style={{
              fontFamily: "'Syne', sans-serif",
              fontWeight: 800,
              fontSize: "clamp(1.6rem, 3vw, 2.4rem)",
              color: c.text,
              marginBottom: 12,
              letterSpacing: "-0.5px",
            }}
          >
            Six Pillars of Intelligence
          </h2>
          <p
            style={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontSize: 16,
              color: c.textMuted,
            }}
          >
            Every module purpose-built for financial fraud detection in India.
          </p>
        </div>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(340px, 1fr))",
            gap: 24,
          }}
        >
          {FEATURES.map((feature, i) => (
            <motion.div
              key={feature.id}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.08 }}
              style={{
                background: c.bgCard,
                border: `1px solid ${c.border}`,
                borderRadius: 16,
                padding: 28,
              }}
            >
              <div
                style={{
                  width: 48,
                  height: 48,
                  borderRadius: 12,
                  background: c.accentLight,
                  border: `1px solid ${c.accent}30`,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  color: c.accent,
                  marginBottom: 16,
                }}
              >
                {feature.icon}
              </div>
              <h3
                style={{
                  fontFamily: "'Syne', sans-serif",
                  fontWeight: 700,
                  fontSize: 18,
                  color: c.text,
                  marginBottom: 10,
                }}
              >
                {feature.name}
              </h3>
              <p
                style={{
                  fontFamily: "'Space Grotesk', sans-serif",
                  fontSize: 14,
                  color: c.textMuted,
                  lineHeight: 1.65,
                  marginBottom: 20,
                }}
              >
                {feature.description}
              </p>
              <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
                {feature.capabilities.map((cap) => (
                  <li
                    key={cap}
                    style={{
                      fontFamily: "'Space Grotesk', sans-serif",
                      fontSize: 13,
                      color: c.textMuted,
                      padding: "5px 0",
                      borderTop: `1px solid ${c.border}`,
                      display: "flex",
                      alignItems: "center",
                      gap: 8,
                    }}
                  >
                    <span
                      style={{
                        width: 6,
                        height: 6,
                        borderRadius: "50%",
                        background: c.accent,
                        flexShrink: 0,
                      }}
                    />
                    {cap}
                  </li>
                ))}
              </ul>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

function FeatureAccordion() {
  const { c } = useTheme();
  const [active, setActive] = useState<string | null>(null);

  return (
    <section style={{ background: c.bg, padding: "80px 24px" }}>
      <div style={{ maxWidth: 800, margin: "0 auto" }}>
        <div style={{ textAlign: "center", marginBottom: 48 }}>
          <h2
            style={{
              fontFamily: "'Syne', sans-serif",
              fontWeight: 800,
              fontSize: "clamp(1.6rem, 3vw, 2.4rem)",
              color: c.text,
              marginBottom: 12,
              letterSpacing: "-0.5px",
            }}
          >
            How Each Feature Works
          </h2>
          <p
            style={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontSize: 16,
              color: c.textMuted,
            }}
          >
            Technical deep-dives for the engineers and analysts behind the screen.
          </p>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          {FEATURES.map((feature) => {
            const isOpen = active === feature.id;
            return (
              <div
                key={feature.id}
                style={{
                  background: c.bgCard,
                  border: `1px solid ${isOpen ? c.accent + "60" : c.border}`,
                  borderRadius: 12,
                  overflow: "hidden",
                  transition: "border-color 0.2s",
                }}
              >
                <button
                  onClick={() => setActive(isOpen ? null : feature.id)}
                  style={{
                    width: "100%",
                    background: "transparent",
                    border: "none",
                    padding: "20px 24px",
                    cursor: "pointer",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "space-between",
                    gap: 16,
                  }}
                >
                  <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
                    <span style={{ color: c.accent }}>{feature.icon}</span>
                    <span
                      style={{
                        fontFamily: "'Syne', sans-serif",
                        fontWeight: 700,
                        fontSize: 16,
                        color: c.text,
                      }}
                    >
                      {feature.name}
                    </span>
                  </div>
                  <span style={{ color: c.textMuted, flexShrink: 0 }}>
                    {isOpen ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                  </span>
                </button>
                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.25 }}
                      style={{ overflow: "hidden" }}
                    >
                      <div
                        style={{
                          padding: "0 24px 24px",
                          borderTop: `1px solid ${c.border}`,
                          paddingTop: 20,
                        }}
                      >
                        {feature.technicalDetail
                          .split("\n\n")
                          .map((para, i) => (
                            <p
                              key={i}
                              style={{
                                fontFamily: "'Space Grotesk', sans-serif",
                                fontSize: 14,
                                color: c.textMuted,
                                lineHeight: 1.75,
                                marginBottom: i === 0 ? 14 : 0,
                              }}
                            >
                              {para}
                            </p>
                          ))}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

function IntegrationAPIs() {
  const { c } = useTheme();
  return (
    <section
      style={{ background: c.bgSecondary, padding: "80px 24px" }}
    >
      <div style={{ maxWidth: 1200, margin: "0 auto" }}>
        <div style={{ textAlign: "center", marginBottom: 56 }}>
          <h2
            style={{
              fontFamily: "'Syne', sans-serif",
              fontWeight: 800,
              fontSize: "clamp(1.6rem, 3vw, 2.4rem)",
              color: c.text,
              marginBottom: 12,
              letterSpacing: "-0.5px",
            }}
          >
            Integration & APIs
          </h2>
          <p
            style={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontSize: 16,
              color: c.textMuted,
            }}
          >
            Plug TRINETRA into your existing workflow in minutes.
          </p>
        </div>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(340px, 1fr))",
            gap: 24,
          }}
        >
          {API_EXAMPLES.map((example, i) => (
            <motion.div
              key={example.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.1 }}
              style={{
                background: c.bgCard,
                border: `1px solid ${c.border}`,
                borderRadius: 16,
                overflow: "hidden",
              }}
            >
              <div
                style={{
                  padding: "16px 20px",
                  borderBottom: `1px solid ${c.border}`,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                }}
              >
                <span
                  style={{
                    fontFamily: "'Syne', sans-serif",
                    fontWeight: 700,
                    fontSize: 15,
                    color: c.text,
                  }}
                >
                  {example.title}
                </span>
                <span
                  style={{
                    fontFamily: "'IBM Plex Mono', monospace",
                    fontSize: 11,
                    color: c.textDim,
                  }}
                >
                  {example.subtitle}
                </span>
              </div>
              <pre
                style={{
                  fontFamily: "'IBM Plex Mono', monospace",
                  fontSize: 12,
                  color: c.textMuted,
                  lineHeight: 1.7,
                  padding: "20px",
                  margin: 0,
                  overflow: "auto",
                  background: c.bgCardSolid,
                  whiteSpace: "pre-wrap",
                  wordBreak: "break-word",
                }}
              >
                {example.code}
              </pre>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

function CTA() {
  const { c } = useTheme();
  return (
    <section
      style={{
        background: c.bg,
        padding: "80px 24px",
        textAlign: "center",
      }}
    >
      <div style={{ maxWidth: 560, margin: "0 auto" }}>
        <h2
          style={{
            fontFamily: "'Syne', sans-serif",
            fontWeight: 800,
            fontSize: "clamp(1.6rem, 3vw, 2.4rem)",
            color: c.text,
            marginBottom: 16,
            letterSpacing: "-0.5px",
          }}
        >
          Start Investigating Now
        </h2>
        <p
          style={{
            fontFamily: "'Space Grotesk', sans-serif",
            fontSize: 16,
            color: c.textMuted,
            marginBottom: 32,
            lineHeight: 1.65,
          }}
        >
          All six features are live in the workspace. Upload documents and see
          TRINETRA's full intelligence stack in action.
        </p>
        <Link
          to="/workspace/hub"
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: 8,
            background: c.accent,
            color: "#fff",
            fontFamily: "'Space Grotesk', sans-serif",
            fontWeight: 700,
            fontSize: 16,
            padding: "14px 32px",
            borderRadius: 10,
            textDecoration: "none",
          }}
        >
          Open Workspace <ArrowRight size={16} />
        </Link>
      </div>
    </section>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export function FeaturesPage() {
  const { c } = useTheme();
  return (
    <div style={{ background: c.bg, minHeight: "100vh" }}>
      <PageNav />
      <Hero />
      <FeatureGrid />
      <FeatureAccordion />
      <IntegrationAPIs />
      <CTA />
    </div>
  );
}
